# Generated by Django 4.1.7 on 2023-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_rename_review_id_userinteraction_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='producer',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
