# Generated by Django 4.1.7 on 2023-03-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
