# Generated by Django 4.1.7 on 2023-03-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_review_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='avg_rating',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='num_rating',
            new_name='reviews',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='en', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='time',
            field=models.CharField(default='2019', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='titleImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default=2018, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_movie', to='movie_app.movie'),
        ),
    ]
