# Generated by Django 4.1.7 on 2023-04-05 23:47

from django.db import migrations, models

def set_url_null(apps, schema_editor):
    MyModel = apps.get_model('movie_app', 'Movie')

    for mm in MyModel.objects.all():

        mm.title_image = ''
        mm.image = ''
        mm.video = ''
        mm.save()

    
class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_alter_watchlist_movie'),
    ]

    operations = [

        migrations.RunPython(set_url_null),
    ]
    
